### ISSUE TITLE
Code should be formatted using prettier

### ISSUE THREAD

**Issue by singingwolfboy** [actions/http-client#18]
Using an automated formatted for code is a good idea, for several reasons:

* It ensures that the code follows a consistent style, which makes it easier to read
* It helps newcomers who are not as familiar with Javascript or Typescript to avoid errors
* It eliminates the time spent thinking about and reviewing the correct way to format code

See https://prettier.io/docs/en/why-prettier.html for more detail on these points.

In the Javascript ecosystem, [Prettier](https://prettier.io) has quickly become the dominant code formatter, for a variety of reasons including execution speed, GitHub stars, tool integration, and simplicity. In fact, `@actions/toolkit`, `@actions/setup-node`, `@actions/typescript-action`, `@actions/labeler`, `@actions/cache`, and `@actions/checkout` are all already using Prettier. For consistency, this project should, as well.

I've already made a pull request for this work: #16.

**Comment by bryanmacfarlane** [comment]
Fixed with #20 and #23 - thanks for pointing this out.  Brings this inline with the other repos like toolkit with the same rules and approach used there.
