### ISSUE TITLE
Remove deprecated URL API usage

### ISSUE THREAD

**Issue by JamieMagee** [actions/http-client#26]
The [legacy URL API](https://nodejs.org/api/url.html#url_legacy_url_api) was deprecated by NodeJS 11 released in October 2018. It is scheduled to be removed in a future release.

Additionally, Yarn v2 does not allow undeclared dependencies to be used. `require('url')` is ambiguous between the built-in NodeJS module, and the npm package [url](https://www.npmjs.com/package/url).

**Comment by bryanmacfarlane** [comment]
merged
