### ISSUE TITLE
Re-enable redirect-to tests once httpbin issue fixed

### ISSUE THREAD

**Issue by dhadka** [actions/http-client#34]
Redirect-to tests are failing due to httpbin issue https://github.com/postmanlabs/httpbin/issues/617 and will be disabled by https://github.com/actions/http-client/pull/33.  This issue is to track re-enabling the tests once the httpbin issue is fixed.

**Comment by joshmgross** [comment]
We should be able to re-enable these tests now.

**Comment by dhadka** [comment]
Opened revert PR - https://github.com/actions/http-client/pull/66

**Comment by dhadka** [comment]
@joshmgross Revert PR passing tests.  I don't have write permissions so can't merge, please do so if the PR looks good.

**Comment by joshmgross** [comment]
Merged, thanks @dhadka
