### ISSUE TITLE
v1.0.9 fails to compile using TypeScript with TS2304 error

### ISSUE THREAD

**Issue by martincostello** [actions/http-client#37]
Using TypeScript with ncc to compile a dist folder as [described in the documentation for actions](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) generates a compilation error when using actions/http-client v1.0.9:

```
Error: node_modules/@actions/http-client/interfaces.d.ts(29,16): error TS2304: Cannot find name 'URL'.
```

[Example build](https://github.com/martincostello/update-dotnet-sdk/runs/1408370916?check_suite_focus=true#step:5:8)

**Comment by martincostello** [comment]
Required an update from `es6` to `es2019` in my `tsconfig.json`.

**Comment by konradpabjan** [comment]
Hit this same problem. My solution was to remove `"lib": ["es6"]` from `tsconfig`. If anyone is curious: https://github.com/actions/toolkit/pull/760#discussion_r608013178
